$logos = @{
  "javascript.svg"   = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/javascript.svg"
  "typescript.svg"   = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/typescript.svg"
  "react.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/react.svg"
  "nextjs.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/nextdotjs.svg"
  "vuejs.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/vuedotjs.svg"
  "angular.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/angular.svg"
  "nodejs.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/nodedotjs.svg"
  "express.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/express.svg"
  "python.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/python.svg"
  "django.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/django.svg"
  "flask.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/flask.svg"
  "php.svg"          = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/php.svg"
  "laravel.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/laravel.svg"
  "springboot.svg"   = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/springboot.svg"
  "csharp.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/csharp.svg"
  "dotnet.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/dotnet.svg"
  "postgresql.svg"   = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/postgresql.svg"
  "mysql.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/mysql.svg"
  "mongodb.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/mongodb.svg"
  "redis.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/redis.svg"
  "firebase.svg"     = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/firebase.svg"
  "aws.svg"          = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/amazonaws.svg"
  "azure.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/microsoftazure.svg"
  "googlecloud.svg"  = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/googlecloud.svg"
  "docker.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/docker.svg"
  "kubernetes.svg"   = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/kubernetes.svg"
  "git.svg"          = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/git.svg"
  "github.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/github.svg"
  "gitlab.svg"       = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/gitlab.svg"
  "tailwindcss.svg"  = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/tailwindcss.svg"
  "bootstrap.svg"    = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/bootstrap.svg"
  "sass.svg"         = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/sass.svg"
  "materialui.svg"   = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/materialui.svg"
  "flutter.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/flutter.svg"
  "ionic.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/ionic.svg"
  "webpack.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/webpack.svg"
  "vite.svg"         = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/vite.svg"
  "jest.svg"         = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/jest.svg"
  "cypress.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/cypress.svg"
  "graphql.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/graphql.svg"
  "linux.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/linux.svg"
  "nginx.svg"        = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/nginx.svg"
  "jenkins.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/jenkins.svg"
  "terraform.svg"    = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/terraform.svg"
  "facebook.svg"     = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/facebook.svg"
  "instagram.svg"    = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/instagram.svg"
  "twitter.svg"      = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/twitter.svg"
  "linkedin.svg"     = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/linkedin.svg"
  "whatsapp.svg"     = "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/whatsapp.svg"
}

$logos.Keys | ForEach-Object {
  $out = "public/logos/$_"
  Invoke-WebRequest -Uri $logos[$_] -OutFile $out
  Write-Host "Downloaded $_"
}