// Mapping of technology/social name to logo filename and brand color
// Place SVGs in public/logos/

export const brandLogos: Record<string, { logo: string; color: string }> = {
  // Skills & Technologies
  'JavaScript': { logo: 'javascript.svg', color: '#F7DF1E' },
  'TypeScript': { logo: 'typescript.svg', color: '#3178C6' },
  'React': { logo: 'react.svg', color: '#61DAFB' },
  'Next.js': { logo: 'nextjs.svg', color: '#000000' },
  'Vue.js': { logo: 'vuejs.svg', color: '#4FC08D' },
  'Angular': { logo: 'angular.svg', color: '#DD0031' },
  'Node.js': { logo: 'nodejs.svg', color: '#339933' },
  'Express.js': { logo: 'express.svg', color: '#000000' },
  'Python': { logo: 'python.svg', color: '#3776AB' },
  'Django': { logo: 'django.svg', color: '#092E20' },
  'Flask': { logo: 'flask.svg', color: '#000000' },
  'PHP': { logo: 'php.svg', color: '#777BB4' },
  'Laravel': { logo: 'laravel.svg', color: '#FF2D20' },
  'Spring Boot': { logo: 'springboot.svg', color: '#6DB33F' },
  'C#': { logo: 'csharp.svg', color: '#239120' },
  '.NET': { logo: 'dotnet.svg', color: '#512BD4' },
  'PostgreSQL': { logo: 'postgresql.svg', color: '#4169E1' },
  'MySQL': { logo: 'mysql.svg', color: '#4479A1' },
  'MongoDB': { logo: 'mongodb.svg', color: '#47A248' },
  'Redis': { logo: 'redis.svg', color: '#DC382D' },
  'Firebase': { logo: 'firebase.svg', color: '#FFCA28' },
  'AWS': { logo: 'aws.svg', color: '#FF9900' },
  'Azure': { logo: 'azure.svg', color: '#0078D4' },
  'Google Cloud': { logo: 'googlecloud.svg', color: '#4285F4' },
  'Docker': { logo: 'docker.svg', color: '#2496ED' },
  'Kubernetes': { logo: 'kubernetes.svg', color: '#326CE5' },
  'Git': { logo: 'git.svg', color: '#F05032' },
  'GitHub': { logo: 'github.svg', color: '#181717' },
  'GitLab': { logo: 'gitlab.svg', color: '#FCA121' },
  'Tailwind CSS': { logo: 'tailwindcss.svg', color: '#06B6D4' },
  'Bootstrap': { logo: 'bootstrap.svg', color: '#7952B3' },
  'SASS/SCSS': { logo: 'sass.svg', color: '#CC6699' },
  'Material-UI': { logo: 'materialui.svg', color: '#007FFF' },
  'React Native': { logo: 'react.svg', color: '#61DAFB' },
  'Flutter': { logo: 'flutter.svg', color: '#02569B' },
  'Ionic': { logo: 'ionic.svg', color: '#3880FF' },
  'Webpack': { logo: 'webpack.svg', color: '#8DD6F9' },
  'Vite': { logo: 'vite.svg', color: '#646CFF' },
  'Jest': { logo: 'jest.svg', color: '#C21325' },
  'Cypress': { logo: 'cypress.svg', color: '#17202C' },
  'GraphQL': { logo: 'graphql.svg', color: '#E10098' },
  'REST API': { logo: 'restapi.svg', color: '#6E57E0' },
  'Microservices': { logo: 'microservices.svg', color: '#FF6F00' },
  'Linux': { logo: 'linux.svg', color: '#FCC624' },
  'Nginx': { logo: 'nginx.svg', color: '#009639' },
  'Jenkins': { logo: 'jenkins.svg', color: '#D24939' },
  'Terraform': { logo: 'terraform.svg', color: '#623CE4' },

  // Social Platforms
  'Facebook': { logo: 'facebook.svg', color: '#1877F3' },
  'Instagram': { logo: 'instagram.svg', color: '#E4405F' },
  'Twitter': { logo: 'twitter.svg', color: '#1DA1F2' },
  'LinkedIn': { logo: 'linkedin.svg', color: '#0077B5' },
  'WhatsApp': { logo: 'whatsapp.svg', color: '#25D366' },
}; 